common/models/Orders.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%orders}}".
 *
 * @property integer $id
 * @property integer $partner_id
 * @property integer $price_id
 * @property integer $car_id
 * @property string $order_date
 * @property string $created_date
 * @property string $approve_date
 * @property boolean $status
 *
 * @property Cars $car
 * @property Partners $partners
 * @property Prices $prices
 * @property Payments[] $payments
 */
class Orders extends \yii\db\ActiveRecord
{
    public $service_id;
    public $car_type_id;
    public $guest;

    public static $status_type = [1 => "Gözləmədə", 2 => "Qəbul olunmuş", 3 => "Bitmiş"];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%orders}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['partner_id', 'price_id', 'order_date', 'created_date'], 'required'],//, 'approve_date'
            [['tour_id','partner_id' , 'price_id', 'car_id', 'status','hotel_id','extra_day'], 'integer'],
            [['order_date', 'created_date', 'approve_date', 'pay_date'], 'safe'],
            [['paid'], 'boolean'],
            [['price'], 'number'],
            [['ip'], 'string', 'max' => 15],
            [['partner_id'], 'exist', 'skipOnError' => true, 'targetClass' => Partners::className(), 'targetAttribute' => ['partner_id' => 'id']],
            [['hotel_id'], 'exist', 'skipOnError' => true, 'targetClass' => Hotels::className(), 'targetAttribute' => ['hotel_id' => 'id']],
            [['car_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cars::className(), 'targetAttribute' => ['car_id' => 'id']],
            [['tour_id'], 'exist', 'skipOnError' => true, 'targetClass' => Tour::className(), 'targetAttribute' => ['tour_id' => 'id']],
            [['price_id'], 'exist', 'skipOnError' => true, 'targetClass' => Prices::className(), 'targetAttribute' => ['price_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tour_id' => 'Tur',
            'partner_id' => 'Partnyor',
            'price_id' => 'Qiymət',
            'car_id' => 'Avtomobil',
            'order_date' => 'Sifariş Tarixi',
            'created_date' => 'Created Date',
            'approve_date' => 'Approve Date',
            'pay_date' => 'Pay Date',
            'status' => 'Status',
            'paid' => 'Ödəniş',
            'price' => 'Qiymət(AZN)',
            'extra_day' => 'Əlavə gün sayı',
            'hotel_id' => 'Otel',
            'car_type_id'=>'Avtomobil növü',
            'ip' => 'Ip',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */


    public function getTour()
    {

        return $this->hasOne(Tour::className(), ['id' => 'tour_id']);
    }

    public function getCar()
    {
        return $this->hasOne(Cars::className(), ['id' => 'car_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrices()
    {
        return $this->hasOne(Prices::className(), ['id' => 'price_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayments()
    {
        return $this->hasMany(Payments::className(), ['orders_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHotels()
    {
        return $this->hasOne(Hotels::className(), ['id' => 'hotel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPartner()
    {
        return $this->hasOne(Partners::className(), ['id' => 'partner_id']);
    }
    
    public static function allStatus()
    {
            return self::$status_type;
    }

    public static function getStatus($key)
    {
        return self::$status_type[$key];
    }

    public function sendEmail()
    {
        $partner = Partners::findOne(Yii::$app->user->identity->partnersid);
        $count_tour = Tour::find()->where(['partner_id'=>Yii::$app->user->identity->partnersid])->count();
        return Yii::$app
            ->mailer
            ->compose(
                ['html' => 'new-tour-html'],
                ['partner' => $partner,'count'=>$count_tour]
            )
            ->setFrom([Yii::$app->params['companyEmail']=> Yii::$app->name . ' robot'])
            ->setTo([Yii::$app->params['companyincomemail'],Yii::$app->params['adminEmail']])
            ->setSubject('Yeni tur sifarişi ' . Yii::$app->name)
            ->send();
    }


    public static function getOrdersCount($partner_id = null,$type = null){

        if ($partner_id == null){
            if ($type  == null){
                $a = self::find()->where('status > 0')->groupBy('tour_id')->count();
            }else{
                $a = self::find()->where(['status'=>$type])->groupBy('tour_id')->count();
            }
        }else{
            if ($type  == null){
                $a = self::find()->where(['partner_id' => $partner_id])->groupBy('tour_id')->count();
            }else{
                $a = self::find()->where(['partner_id' => $partner_id,'status'=>$type])->groupBy('tour_id')->count();
            }
        }




        return $a;
    }

    public static function getOrdersAmount($partner_id = null,$type = null)
    {
        if ($type == null)
        {
            $where = " O.status > 0 ";
        }else if ($type == 'paid'){
            $where = " O.paid = 1 ";
        }else if($type == 'residual') {
            $where = " O.paid = 0 AND O.status > 0 ";
        }
        if ($partner_id == null){
            $sumprice = Yii::$app->db->createCommand("SELECT
                                                    SUM(O.price) AS lastsum,
                                                    SUM(P.price_partner) AS sumprice,
                                                    SUM(O.extra_day) as sumextraday
                                                FROM
                                                    cms_orders O
                                                        LEFT JOIN
                                                    cms_prices P ON O.price_id = P.id
                                                WHERE
                                                    $where ")->queryOne();

        }else
        {
            $sumprice = Yii::$app->db->createCommand("SELECT
                                                    SUM(O.price) AS lastsum,
                                                    SUM(P.price_partner) AS sumprice,
                                                    SUM(O.extra_day) as sumextraday
                                                FROM
                                                    cms_orders O
                                                        LEFT JOIN
                                                    cms_prices P ON O.price_id = P.id
                                                WHERE
                                                    O.partner_id =:partner_id AND $where ")->bindValue(":partner_id",$partner_id)->queryOne();

        }

        $sp = ($sumprice['lastsum'])?$sumprice['lastsum']:0;

        return Yii::$app->formatter->asCurrency($sp, 'AZN');

    }

    public static function incomeDriver($car_id)
    {
        $driver_income_sum = Yii::$app->db->createCommand("SELECT 
                                                            sum(P.price_driver + (O.extra_day * P.driver_extra_day_price)) as  driver_income_sum
                                                        FROM
                                                            cms_orders O
                                                            INNER JOIN cms_prices P ON O.price_id = P.id
                                                        WHERE
                                                            car_id =:car_id")->bindValue(":car_id",$car_id)->queryScalar();

        return $driver_income_sum;
    }

    public static function ordersCountDriver($car_id)
    {
         $count_order =   Yii::$app->db->createCommand("SELECT count(id) as  count_order FROM  cms_orders O WHERE car_id =:car_id")->bindValue(":car_id",$car_id)->queryScalar();
         return $count_order;
    }




    public static function priceTotal($provider, $fieldName)
    {
        $total=0;
        foreach($provider as $item){
            $total+=$item[$fieldName];
        }
        return $total;
    }

}

backend/controllers/TourController.php
<?php

namespace backend\controllers;

use common\models\Orders;
use Yii;
use common\models\Tour;
use backend\models\TourSearch;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TourController implements the CRUD actions for Tour model.
 */
class TourController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        //'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tour models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TourSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tour model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tour model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tour();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Tour model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDetail($id){
        $tour_id = $id;
        $dataProvider = new ActiveDataProvider([
            'query' => Orders::find()->where(['tour_id'=>$tour_id]) ->orderBy('order_date ASC'),
            'sort' => false,
            //'sort'=> ['defaultOrder' => ['id' => SORT_DESC],'attributes' => []]
        ]);
        return $this->renderPartial('_gettourorders',['dataProvider' => $dataProvider,]);
    }


    public function actionPay($id)
    {
        $order  = $this->findModel($id);
        $order->paid = 1;
        if ($order->save(false)){
            Orders::updateAll(['paid'=>1,'pay_date'=>date("Y-m-d H:i:s")],['tour_id'=>$id]);
            return true;
        }
    }

    public function actionChangestatus($id,$type){
        $order  = $this->findModel($id);
        if ($type == 'allow')
            $order->status = 2;
        else if ($type == 'complate')
            $order->status = 3;

        if ($order->save(false)){
            if ($order->status == 2){
                Orders::updateAll(['status'=>$order->status,'approve_date'=>date("Y-m-d H:i:s")],['tour_id'=>$id]);
            }else{
                Orders::updateAll(['status'=>$order->status],['tour_id'=>$id]);
            }


            return true;
        }
    }

    public function actionExport($id = null,$price =null){

        if ($price == null)
            return $this->render('_confirm',['id'=>$id]);

        if ($id == null)
            $tour  = Tour::find()->where(['status'=>1])->all();
        else
            $tour  = Tour::find()->where(['id'=>$id])->all();

        $content = $this->renderPartial('_export',[ 'tours' => $tour,'price'=>$price]);
        //return $content;
        $pdf = Yii::$app->pdf;
        $pdf->content = $content;
        return $pdf->render();
    }

    public function actionNotification()
    {
        $new_tour   = Yii::$app->db->createCommand("select count(*) from cms_tours WHERE UNIX_TIMESTAMP(create_date) > (UNIX_TIMESTAMP(now()) - 60) ;")->queryScalar();

        if ($new_tour > 0)
            return $new_tour;
    }


    /**
     * Deletes an existing Tour model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tour model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tour the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tour::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/tour/_confirm.php
<?php
use yii\helpers\Url;
?>
<div class="panel panel-default">
    <div class="panel-heading">
        Qiymət çap olunsun ?
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">

            <a href="<?=Url::to(['tour/export','id'=>$id,'price'=>'yes'])?>" class="btn btn-primary btn-lg ">Qiymələr çap olunsun</a>
            <a href="<?=Url::to(['tour/export','id'=>$id,'price'=>'no'])?>" class="btn btn-default btn-lg ">Qiymələr çap olunmasın</a>

        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>

frontend/views/tour/_export.php
<?php
use common\models\Orders;
?>

<h1 class="text-center">Turlar(<?=$tours[0]->partner->company?>)</h1>

<table class="table table-bordered">
    <thead>
    <tr>
        <th width="10">#</th>

        <th>Tur</th>
        <th>Tarix</th>
        <th>Qonaq</th>
        <?php
        if ($price == 'yes'){
            ?>
            <th>Qiymət</th>
            <?php
        }
        ?>

    </tr>
    </thead>
    <tbody>
<?php
foreach ($tours as $k => $tour) {
    ?>


        <tr>
            <td><?=($k+1)?></td>
            <td>Tur-<?=$tour->id?></td>
            <td><?=$tour->create_date?></td>
            <td><?=$tour->guest?></td>
            <?php
            if ($price == 'yes'){
                ?>
                <td><?=Yii::$app->formatter->asCurrency($tour->price, 'AZN')?></td>
                <?php
            }
            ?>
        </tr>
        <tr>
            <td colspan="<?=($price == 'yes')?'5':'4'?>">
                <table class="table">
                    <thead>
                    <tr>
                        <th >#</th>
                        <th>İstiqamət</th>
                        <th>Avto ban</th>
                        <th>Əlavə gün</th>
                        <th>Sifariş tarixi</th>
                        <th>Otel</th>
                        <th>Sürücü</th>
                        <th>Avtomobil nömrəsi</th>
                        <?php
                        if ($price == 'yes'){
                            ?>
                            <th>Qiymət</th>
                            <?php
                        }
                        ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $orders = Orders::find()->where(['tour_id'=>$tour->id])->all();
                    foreach ($orders as $k => $order) {
                        ?>
                        <tr>
                            <td><?=($k+1)?></td>
                            <td><?=$order->prices->service->title?></td>
                            <td><?=$order->prices->carType->title?></td>
                            <td><?=$order->extra_day?></td>
                            <td><?=$order->order_date?></td>
                            <td><?=$order->hotels->title?></td>
                            <?php
                            if (isset($order->car_id)):
                            ?>
                            <td><?=$order->car->driver.'('.$order->car->phone.')'?></td>
                            <td><?=$order->car->car_number?></td>
                            <?php
                                else:
                                ?>
                                    <td>----</td>
                                    <td>----</td>
                            <?php
                                endif;
                                ?>

                            <?php
                            if ($price == 'yes'){
                                ?>
                                <td><?=Yii::$app->formatter->asCurrency($order->price, 'AZN')?></td>
                                <?php
                            }
                            ?>
                        </tr>
                        <?php
                    }
                    ?>
                    </tbody>
                </table>
            </td>
        </tr>

    <?php
}
?>
</tbody>
</table>

frontend/views/tour/index.php
<?php

use common\models\Orders;
use common\models\Tour;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\TourSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Turlar';
$this->params['breadcrumbs'][] = $this->title;
$partner = Yii::$app->user->identity->partnersid;
?>
<style>
    #w0 table tr.tour td:first-child {
        cursor: pointer;
    }
</style>
<div class="tour-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('<i class="glyphicon glyphicon-ok"></i> Tur əlavə et', ['orders/createajax'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('<i class="glyphicon glyphicon-print"></i> Hamısın Çap et', ['tour/export'], ['class' => 'btn btn-warning' ,'target'=>'_blank']) ?>
    </p>


    <div class="panel panel-default">
        <div class="panel-heading">
            Bütün turlar
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body table-responsive">
<?php Pjax::begin(['id' => 'tours_grid']); ?>
    <?= GridView::widget([
        'dataProvider'  =>  $dataProvider,
        'filterModel'   =>  $searchModel,
        'showFooter'    =>  true,
        'footerRowOptions'=>['style'=>'font-weight:bold;'],
        //'summary' => '',
        'rowOptions' => function ($model) {
            switch ($model->status){
                case 1:
                    return ['class' => 'tour warning' ,'data-id'=>$model->id];//accepted
                    break;
                case 2:
                    return ['class' => 'tour success' ,'data-id'=>$model->id];//
                    break;
                case 3:
                    return ['class' => 'tour info' ,'data-id'=>$model->id];
                    break;
            }
        },
        'columns' => [
            [
                'label' => '',
                'value' => function($model){
                    return "<i class='glyphicon glyphicon-expand'  data-id='".$model->id."' ></i>";
                },
                'format' => 'raw',

            ],

            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            [
                'attribute' => 'id',
                'value' => function($model){
                    return "Tur-".$model->id;
                },
            ],

            #'partner_id',
            //'status',

            'guest',
            [
                'attribute' => 'price',
                'value' => function($model){
                    return Yii::$app->formatter->asCurrency($model->price, 'AZN');
                },
                'footer'=>Yii::$app->formatter->asCurrency(Tour::priceTotal($dataProvider->models,'price'), 'AZN'),
            ],

            //'price',
            'create_date',
            /*[
                'attribute' => 'create_date',
                'format' => ['date', 'php:d-m-Y H:i:s']
            ],*/

            [
                'attribute' => 'status',
                'value'     => function($dataProvider){
                    return Orders::getStatus($dataProvider->status);//gettype($dataProvider->status);
                },
                'filter'    =>Orders::allStatus(),

            ],
            [
                'label' => 'Çap et',
                'format'=>'raw',
                'value' => function($model){
                    return Html::a('<i class="glyphicon glyphicon-print"></i> Çap et', '#', ['onclick' => "window.open ('".Url::toRoute(['tour/export','id'=>$model->id])."'); return false",'class' => 'btn btn-warning','target'=>'_blank']);
                },
            ],
           // ['class' => 'yii\grid\ActionColumn'],

            [
                'class'     => 'yii\grid\ActionColumn',
                'template'  => '{delete}',

                'buttons' => [
                    'delete' => function($url, $model){
                        if ($model->status == 1){
                            return  Html::a('<span class="glyphicon glyphicon-trash"></span>', ['delete', 'id' => $model->id], [
                                'class' => 'btn btn-danger',
                                'title' => 'Sil',
                                'data' => [
                                    'confirm' => 'Silmək istədiyinizdən əminsiniz ?',
                                    'method' => 'post',
                                ],
                            ]);
                        }

                    }
                ]
            ],
        ],
    ]); ?>

    <?php
    $this->registerJs('
        $( "#w0 tbody tr.tour td:first-child" ).click(function() {
         var service = $(this).val(); 
         var form = $(this);
         var showbtn = form.find("i");  
         var tour_id = showbtn.data("id");
         var cls =  "child-"+tour_id;        
             
       if (form.parent().next().hasClass(cls))
       {      
            if (showbtn.hasClass("glyphicon-collapse-down"))
                showbtn.removeClass("glyphicon-collapse-down").addClass("glyphicon-expand");
            else
                showbtn.removeClass("glyphicon-expand").addClass("glyphicon-collapse-down");    
            
            $("."+cls).toggleClass("hide");
       }else{
            showbtn.removeClass("glyphicon-expand").addClass("glyphicon-collapse-down");
           $.get({
          url: "' . Yii::$app->urlManager->createUrl('orders/gettourorders') . '",
          data: { "id": tour_id},
          success: function(data){
             
               form.parent().after("<tr class =\""+cls+"\"><td colspan=\"9\">"+data+"</td></tr>"); 
          },      
        });
       }        
});

'
    );
    ?>
<?php Pjax::end(); ?></div>

    </div>
</div>
<?php
$this->registerJs("
            setInterval(function(){ $.pjax.reload({container: '#tours_grid'}); }, 1000*60);
");
?>

<div class="row">
    <div class="col-md-6">


        <div class="panel panel-default">
            <div class="panel-heading">
                Sifariş sayı
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered">

                        <tr>
                            <th>Ümumi sifarişlər</th>
                            <th>Gözləmədə</th>
                            <th>Qəbul olunmuş</th>
                            <th>Bitmiş</th>
                        </tr>

                        <tr>
                            <td><?=Orders::getOrdersCount($partner)?></td>
                            <td><?=Orders::getOrdersCount($partner,1)?></td>
                            <td><?=Orders::getOrdersCount($partner,2)?></td>
                            <td><?=Orders::getOrdersCount($partner,3)?></td>
                        </tr>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>


    </div>

    <div class="col-md-6">

        <div class="panel panel-default">
            <div class="panel-heading">
                Sifariş məbləğləri
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered">

                        <tr>
                            <th>Ümumi məbləğ</th>
                            <th>Ödənilmiş</th>
                            <th>Qalıq</th>
                        </tr>

                        <tr>
                            <td><?=Orders::getOrdersAmount($partner)?></td>
                            <td><?=Orders::getOrdersAmount($partner,'paid')?></td>
                            <td><?=Orders::getOrdersAmount($partner,'residual')?></td>
                        </tr>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>


    </div>
</div>